#!/bin/bash
#read -p "How many files need to be compiled [1 - 10]: " appfiles

if [[ $# -lt 1 ]]; then
    echo "Error: No master file listed... Usage: ./compile.sh <master-file>.ts"
    exit 0
elif [[ $# -gt 1 ]]; then
    echo "Error: Only one master file can be used... Usage ./compile.sh <master-file>.ts"
    exit 0
fi

userdir=$`pwd`

if [[ -d /tmp/tstemp ]]; then
    echo "tstemp directory previously created, deleting files and moving on..."
    rm -r /tmp/tstemp
    mkdir /tmp/tstemp
else
    mkdir /tmp/tstemp
    echo "tstemp directory created..."
fi


master=$1
appdir=`pwd`
filecount=0
reffile=0
appfiles=0

cp $master /tmp/tstemp/master.ts

for item in `find -name "*.ts" -or -name "*.d.ts"`; do
    if [[ $item =~ \.d.ts$ ]]; then
	  reffile=$[$reffile + 1]
	  cp $item /tmp/tstemp/
       elif [[ $item =~ \.ts$ ]] && [[ $item != $master ]]; then
	     filecount=$[$filecount + 1]
	     cp $item /tmp/tstemp/file$filecount.ts
    fi
done


cd /tmp/tstemp

for (( i = 1; i <= $filecount; i++))
do
	removeLineFrom=file$i.ts
	if [[ $removeLineFrom = $master ]]; then
	    echo "Master File"
	else
	    sed -i 's_/// <reference path=_//_g' $removeLineFrom
	fi
done

cd ..

echo "Any errors that occur past this point are generated by TypeScript compiler:"
echo "----------------------------------------------------------------"

tsc --out app.js /tmp/tstemp/*.ts

#rm -r tstemp

#echo "tstemp directory removed"
