#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Error: No master file listed... Usage: ./compile.sh <master-file>.ts"
    exit 0
elif [[ $# -gt 1 ]]; then
    echo "Error: Only one master file can be used... Usage ./compile.sh <master-file>.ts"
    exit 0
fi

if [[ -d /tmp/tstemp ]]; then
    echo "tstemp directory previously created, deleting files and moving on..."
    rm -r /tmp/tstemp
    mkdir /tmp/tstemp
else
    mkdir /tmp/tstemp
    echo "tstemp directory created..."
fi


master=$1
filecount=0

cp $master /tmp/tstemp/master.ts

for item in `find -name "*.ts" -or -name "*.d.ts"`; do
    if [[ $item =~ \.d.ts$ ]]; then
	  cp $item /tmp/tstemp/
       elif [[ $item =~ \.ts$ ]] && [[ $item != $master ]]; then
	  filecount=$[$filecount + 1]
	  cp $item /tmp/tstemp/file$filecount.ts
    fi
done

echo "File Count: $filecount"

cd /tmp/tstemp

for (( i = 1; i <= $filecount; i++))
do
    sed -i 's_/// <reference path=_//_g' file$i.ts
done

cd ..

echo "Any errors that occur past this point are generated by TypeScript compiler:"
echo "----------------------------------------------------------------"

tsc --out app.js /tmp/tstemp/*.ts

#rm -r tstemp

#echo "tstemp directory removed"
